### ISSUE TITLE
Pre 0.6.0 bugs

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#171]
Batch 1:
- [x] Binder special crashes 42163b56b010f95fb8bbe0d104dce5a8589c829e
- [x] Magic Immunity special doesn't work, magic towers can deal damage e40923dea3f9e7e331910b1fd14153f274a3d66f
- [x] Transforming towers doesn't "spend" the tower in stash 46e5ff268e0ee75cfb70ffab8d9c26ee032cb282
- [x] Item216 (Pendant of Mana Supremacy) crashes d35d279bc318a29cf0f6c0847267a1c7ba6f1722
- [x] Chrono Jumper item is not usable - not a bug, this item is currently disabled
- [x] Distorted Idol item doesn't work - not a bug, this item is currently disabled
- [x] Can upgrade elements past max level c05a2733cbbcd8950222bf157105ed3f2bf55f86
- [x] Phantom tower crashes when using skill 768ce58f34e88f7917513ddcb73494a3c1a72e54
- [x] Phantom tower always buffs itself, should buff other towers sometimes as well 7aaccf58b7eb5b5e23d131fe04057cab0d672320
- [x] Can't select targets when manually casting ability of Phantom tower ec47b7f28abdf2aa70e7f84632fb2b9086fa6744
- [x] Ruined Tower drops items on the ground, should fly them to stash 42488f056347ca4e9f874240adfd209918a64706
- [x] Items should fly to stash when spawned via debug menu a4d117b138442b73422b2d13a24c9f4216481cd4
- [x] get_exp_for_level() causes error when it's called for level 26 c2f399f775adc39a3ddf0c15224b0738c89d59e9
- [x] Bounce attacks hit only one creep in normal waves d92db4023767eff2507bb06cf2d405c13019278a
- [x] Scroll of Strength and Scroll of Speed don't work 425760bdd43861fa22110b75c39aec1046357846
- [x] Frost Fire towers don't cast their ability b698a917def1e3ebfd8f2cb3217a793dbba2607b
- [x] Can't click on towers below messages on left side of screen a72b946c91d7d9af13b51681c7d91d53a9bac754
- [x]  Pocket Rocket tower has incorrect attack type 31d70c29c5ea74f169b9950f5b689ed5197762bf
- [x] Tooltip for Ball Lightning item doesn't mention that it increases attack speed 439bb24d333d64ed2762d257fc926e18e67e6059
- [x] Chameleon Glaive's ability fires projectiles which fly together with normal projectile, add a delay or change speed of projectile - added a delay of 0.1s bf7845cc5d70ca58133586363d9ce23b5869a02c
- [x] Pocket Emporium doesn't have charges - it does have charges, the problem is that the display of charges was not implemented ff43bf54e3e71c8f31091ce7ec7f62b2183e4cc7
- [x] Spellbook of Item Mastery crashes 9fbfa85f786bfa32b6ce695a39e6242632b28121
- [x] Priest Figurine item not applying buff - not a bug, it doesn't apply a buff and instead modifies the MOD_EXP_GRANTED stat of the creep directly. Note that you won't be able to see this stat in the info in tower menu when creep is selected because that menu shows tower stats ("on kill", not "on death")
- [x] Item stash lags when it has 200+ items - will fix after 0.6.0 #172
- [x] Elune's Bow decreases damage below base damage when it's not supposed to - caused by base damage being randomized 317e9dddaa11943528349e4487163187dfea7d8d
- [x] Incorrect floating text for exp losses be675bc8da3173acabe3ceb4911a12cfe56099a2
- [x] Item42 (Sleeve of Rage) causes error ec8e9badf73d039036b7f33f3ea6f1ab78be0530
- [x] Item201 (Even More Magical Hammer) is broken 792bfdc74d74cc1c865e6b9820ba14fbe0ea854b
- [x] Aoe damage is calculated incorrectly, for example Snowy Pebble tower deals only 1 damage to all creeps in range, supposed to deal 25% of base damage df74d3bca00a31fd9ec9071cfe2ce5cbbb88472c
- [x] Item247 (Chameleons Soul) causes runtime error b900810bab3f27a9b4263fbf7525ba193951914e
- [x] Mana Shield special doesn't work correctly, creeps die instantly 48843f84f1578d3fd122ec0186cec3228442471a

Batch 2:
- [x] Item255 (Ball Lightning) stops the game if there is only one tower 67945ce739615b224768102b93b9038bf8d0d616
- [x] Item255 (Ball Lightning) drops item on the ground if there is only one tower 0f78907a14d31d86757a138ca78268074c7b97e0
- [x] Need special wave timing for Extreme difficulty - will fix after 0.6.0 #176
- [x] Floating text is not fading at the end 50eed097007595454b3288f8d9da500dad031de2
- [x] Old hunter item should not transfer exp to carrier on kill if there are no towers in range, same with Share Knowledge 67945ce739615b224768102b93b9038bf8d0d616
- [x] Arms Dealer doesn't take into account tower's bounty ratio - not a bug, Arms Dealer script uses give_gold() which doesn't take into account tower's bounty ratio
- [x] Shining Rock doesn't show +N exp floating text when picked up by tower 95bf6865fede99ba2babbca10801fa027dcdc71a
- [x] Item cooldowns are reset when item is removed from tower, for example Toy Boy item - will fix after 0.6.0 #175
- [x] Mind Leecher hangs the game 67945ce739615b224768102b93b9038bf8d0d616
- [x] Bloodthirsty Wheel of Fortune should make floating texts with different colors (note, the colors are red/blue according to original script) f3020b46d916b9c84d19092c195c7403d8fe5904
- [x] Basics of Calculus item should grant +1exp as base amount, instead it gives 0 19be8f4175a3298c552f3471017c58d48adf5cd3
- [x] Commander item adds negative debuff instead of buff cc8c0de62431a7dff8e52e170fb0ddfbefe3dad3
- [x] Commander item doesnt buff attackspeed like it should cc8c0de62431a7dff8e52e170fb0ddfbefe3dad3
- [x] Wand of Mana Zap shows +0 floating text for creeps without mana 4a3739d4761d1c12128fcf17de48de215b4bc550
- [x] Can't toggle automatic casting for item abilities - will fix after 0.6.0 #177
- [x] Items with charges keep trying to cast ability while charge is 0 - will fix after 0.6.0 #178
- [x] Haunted Hand item allows tower to attack creeps outside of tower range a21555c5c05b757d727ba14f8f52e305151c7c74
- [x] Sign of Energy Infusion doesn't work correctly 2c47b6f81915e0238f4f8de4bb2c2d780ec56f02
- [x] Projectiles keep moving while game is paused 1404ef2fbb046c9f6c61309aa37bbae8db77cfe4
- [x] Towers with Magic attack still attack immune creeps, they should ignore them 092f5dde3c7ee3cb4e7fcaab1ef5b4c45a7ced2a
- [x] Drain wave special doesn't drain mana from towers 1a05645e60350193cb36aec5bd863b623c1e2e4f
- [x] Evasion special shouldn't affect spells or active abilities, currently it affects all sources of damage 2e1870ce76a839fdfb74f66275279421b09b5a53
- [x] Conversion between pixels and wc3 units is incorrect. For example Stormy Dog ability in original game affects towers up to 3 tiles away. In godot game, Stormy Dog affects towers up to 4 tiles away. 70cdd657c0dbb37840205d31fb9b441d46f008e9
- [x] Unyielding Maul shows "Miss" text but damage doesn't get reduced to 0 9060858f41ace3d17467be7d900026198b85d790
- [x] Jungle Stalker's Doll buff is unfriendly when it should be friendly c0961b4902a8fc8f7e1b37de2301df5e266c761a
- [x] Some sfx are too loud, specifically tower effects and specifically in html5 build a12923aeaebe8c059a174064304b76473dc28be5
- [x] Replacing Lunar Sentinal creates infinite animation - will fix after 0.6.0 #180
- [x] Healing Shrine restores too much hp (couldn't reproduce)
- [x] Magic Hammer doesn't work (couldn't reproduce)
