### ISSUE TITLE
Reduce unique sprites for common tower upgrades

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#89]
**Prerequisites**
To complete this task, you will need access to our [tower sprites](https://drive.google.com/drive/folders/10yNcUe3uT87DD0WPacQPUutjIntSRG7c). Ask @Kvel2D or @Praytic to provide you with these sprites.

**Task**
Common towers should have 1 unique sprite per 2 upgrades, the second upgrade is just an increased sprite of the previous upgrade.

**Darkness**

- [x] Tombstone
- [x] Haunted Rubble
- [x] Dark Fire Pit
- [x] Tentacle Spawn
- [x] Lesser Dark Defender
- [x] Small Frost Fire
- [x] Broken Cage

**Fire**

- [x] Fiery Pebble
- [x] Small Fire Sprayer
- [x] Felweed
- [x] Lesser Flamy Defender
- [x] Small Torch
- [x] Broken Fire Pit

**Nature**

- [x] Tiny Shrub
- [x] Small Cactus
- [x] Tree Stump
- [x] Lesser Natural Defender
- [x] Baby Plant

**Storm**

- [x] Ruined Storm Cap
- [x] Ruined Monolith
- [x] Lesser Storm Defender
- [x] Broken Lightning Rod
- [x] Rotted Flashing Grave

**Iron**

- [x] Obelisk of Fortuity
- [x] Trash Heap
- [x] Mossy Acid Sprayer
- [x] Small Pocket Rocket
- [x] Abandoned Pit
- [x] Lesser Iron Defender

**Astral**

- [x] Astral Lantern
- [x] Ruined Sun Pedestal
- [x] Glowing Solar Orb
- [x] Minor Magic Ruin
- [x] Lesser Astral Defender

**Ice**

- [x] Frost Root
- [x] Snowy Pebble
- [x] Abominable Snowman
- [x] Icy Skulls
- [x] Lesser Ice Defender
- [x] Small Frozen Mushroom
